contact_links:
  - name: "\u2709\uFE0F Email"
    url: https://mailxto.com/gj5bni0yvt
    about: Send an email to the TSML developers at M.B.Middlehurst@gmail.com. Checked periodically.
  - name: "\U0001F310 TSC Webpage"
    url: https://www.timeseriesclassification.com/
    about: The TSML research group and TSC dataset archive website.
