name: ✨ Feature request
description: Suggest a new algorithm or idea for tsml-eval.
title: "[ENH] "
labels: ["enhancement"]

body:
- type: textarea
  attributes:
    label: Describe the feature or idea you want to propose
    description: >
      Is your feature request related to a problem? Please describe. If relevant, you
      should link to a paper or other reference.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe your proposed solution
    description: >
      A clear and concise description of what you want to happen, ideally taking into
      consideration the existing package design, classes and methods.
  validations:
    required: true
- type: textarea
  attributes:
    label: Other comments and alternatives considered
    description: >
      Add any other context or comments, or alternative solutions relating to the
      problem here.
