"""Tests for the Random Shapelet Forest estimators."""

import numpy as np
import pytest

from tsml.datasets import load_minimal_chinatown, load_minimal_gas_prices
from tsml.shapelet_based import (
    RandomShapeletForestClassifier,
    RandomShapeletForestRegressor,
)
from tsml.shapelet_based._rsf import (
    _argsort,
    _euclidean_distance,
    _within_threshold,
)
from tsml.utils.testing import generate_3d_test_data


def test_rsf_classifier_matches_wildboar():
    """Test predictions match those of wildboar 1.2.0 using the same trees.

    Expected values were generated by fitting wildboar ShapeletTreeClassifier
    estimators with the case weights and seeds used by this forest.
    """
    X_train, y_train = load_minimal_chinatown("TRAIN")
    X_test, _ = load_minimal_chinatown("TEST")

    rsf = RandomShapeletForestClassifier(n_estimators=5, random_state=0)
    rsf.fit(X_train, y_train)
    proba = rsf.predict_proba(X_test)

    expected = np.array(
        [0.8, 0.8, 0.6, 1.0, 1.0, 1.0, 0.8, 0.8, 0.6, 0.8]
        + [0.2, 0.2, 0.8, 0.0, 0.2, 0.8, 0.2, 0.2, 0.2, 0.4]
    )
    np.testing.assert_array_equal(proba[:, 0], expected)


def test_rsf_regressor_matches_wildboar():
    """Test predictions match those of wildboar 1.2.0 using the same trees.

    Without bootstrapping, all case weights are 1. wildboar computes the squared
    error impurity incorrectly for other weights, so its trees differ when
    bootstrapping.
    """
    X_train, y_train = load_minimal_gas_prices("TRAIN")
    X_test, _ = load_minimal_gas_prices("TEST")

    rsf = RandomShapeletForestRegressor(n_estimators=5, bootstrap=False, random_state=0)
    rsf.fit(X_train, y_train)
    pred = rsf.predict(X_test)

    expected = np.array(
        [
            -0.3188575550455313,
            -0.3137267827987671,
            -0.42905801879671907,
            -0.22273496475357274,
            -0.30734842886145297,
            -0.24570231192387068,
            -0.328501794888423,
            -0.32118165254592895,
            -0.35069229607398694,
            -0.33757846097533517,
            -0.26503558067175054,
            -0.3285854382010606,
            -0.367835905116338,
            -0.204845100492239,
            -0.3426492859308536,
            -0.328501794888423,
            -0.409087166098448,
            -0.3400582586458095,
            -0.204845100492239,
            -0.27904755897246875,
        ]
    )
    np.testing.assert_array_equal(pred, expected)


def test_argsort():
    """Test the introsort port sorts values and applies the same swaps."""
    rng = np.random.RandomState(0)
    for n in [0, 1, 2, 5, 50, 500]:
        # few unique values to exercise ties
        values = rng.randint(0, 10, size=n + 3).astype(np.float64)
        samples = np.arange(n + 3, dtype=np.int64)
        original = values.copy()

        _argsort(values, samples, 2, n)

        np.testing.assert_array_equal(values[2 : n + 2], np.sort(original[2 : n + 2]))
        np.testing.assert_array_equal(values, original[samples])
        np.testing.assert_array_equal(values[:2], original[:2])
        np.testing.assert_array_equal(values[n + 2 :], original[n + 2 :])


def test_euclidean_distance():
    """Test the shapelet distance is the minimum distance over all subsequences."""
    rng = np.random.RandomState(0)
    X = rng.normal(size=(3, 2, 20))
    s = rng.normal(size=20)

    for start, length in [(0, 1), (2, 5), (0, 10), (1, 19), (0, 20)]:
        shapelet = s[start : start + length]
        expected = min(
            np.sqrt(np.sum((X[1, 1, i : i + length] - shapelet) ** 2))
            for i in range(20 - length + 1)
        )
        dist = _euclidean_distance(X[1, 1], shapelet, 0)
        assert np.isclose(dist, expected)

        # the subsequence compared first does not change the result
        for first in range(20 - length + 1):
            assert _euclidean_distance(X[1, 1], shapelet, first) == dist


def test_within_threshold():
    """Test the threshold check matches comparing the distance to the threshold."""
    rng = np.random.RandomState(0)
    X = rng.normal(size=(6, 30))

    for length in [1, 2, 8, 9, 17, 30]:
        for start in [0, (30 - length) // 2, 30 - length]:
            shapelet = X[0, start : start + length].copy()
            for x in X:
                dist = _euclidean_distance(x, shapelet, start)
                thresholds = [
                    0.0,
                    1e-200,
                    dist / 2,
                    np.nextafter(dist, 0),
                    dist,
                    np.nextafter(dist, np.inf),
                    dist * 2,
                    np.inf,
                ]
                for threshold in thresholds:
                    assert _within_threshold(x, shapelet, start, threshold) == (
                        dist <= threshold
                    )


@pytest.mark.parametrize(
    "params",
    [
        {"n_shapelets": "log2"},
        {"n_shapelets": "sqrt", "alpha": 0.5},
        {"n_shapelets": lambda n: n // 10},
        {"alpha": -0.5, "criterion": "gini"},
        {"min_shapelet_size": 0.3, "max_shapelet_size": 0.6, "max_depth": 2},
        {"class_weight": "balanced", "bootstrap": False},
    ],
)
def test_rsf_classifier_params(params):
    """Test RandomShapeletForestClassifier with different parameters."""
    X, y = generate_3d_test_data(n_samples=20, n_channels=2, random_state=0)

    rsf = RandomShapeletForestClassifier(n_estimators=3, random_state=0, **params)
    rsf.fit(X, y)
    proba = rsf.predict_proba(X)

    assert proba.shape == (20, 2)
    np.testing.assert_allclose(proba.sum(axis=1), 1)

    if params.get("max_depth") is not None:
        assert all(
            _tree_depth(tree.left, tree.right) <= params["max_depth"]
            for tree in rsf.estimators_
        )


def _tree_depth(left, right, node=0):
    if left[node] == -1:
        return 0
    return 1 + max(
        _tree_depth(left, right, left[node]), _tree_depth(left, right, right[node])
    )


def test_rsf_oob_score():
    """Test the out-of-bag estimates."""
    X, y = generate_3d_test_data(n_samples=20, random_state=0)
    rsf = RandomShapeletForestClassifier(
        n_estimators=10, oob_score=True, random_state=0
    )
    rsf.fit(X, y)
    assert 0 <= rsf.oob_score_ <= 1
    assert rsf.oob_decision_function_.shape == (20, 2)

    X, y = generate_3d_test_data(n_samples=20, regression_target=True, random_state=0)
    rsf = RandomShapeletForestRegressor(n_estimators=10, oob_score=True, random_state=0)
    rsf.fit(X, y)
    assert rsf.oob_prediction_.shape == (20,)
    assert np.isfinite(rsf.oob_score_)


def test_rsf_n_jobs():
    """Test results do not depend on the number of jobs."""
    X, y = generate_3d_test_data(n_samples=20, random_state=0)
    proba = (
        RandomShapeletForestClassifier(n_estimators=4, random_state=0, n_jobs=1)
        .fit(X, y)
        .predict_proba(X)
    )
    proba_parallel = (
        RandomShapeletForestClassifier(n_estimators=4, random_state=0, n_jobs=2)
        .fit(X, y)
        .predict_proba(X)
    )
    np.testing.assert_array_equal(proba, proba_parallel)


@pytest.mark.parametrize(
    "params, msg",
    [
        ({"n_estimators": 0}, "n_estimators"),
        ({"min_shapelet_size": -0.1}, "min_shapelet_size"),
        ({"max_shapelet_size": 1.5}, "max_shapelet_size"),
        ({"min_shapelet_size": 0.6, "max_shapelet_size": 0.5}, "min_shapelet_size"),
        ({"alpha": 0.0}, "alpha"),
        ({"oob_score": True, "bootstrap": False}, "bootstrap"),
        ({"criterion": "squared_error"}, "criterion"),
        ({"n_shapelets": "invalid"}, "n_shapelets"),
    ],
)
def test_rsf_invalid_params(params, msg):
    """Test invalid parameters raise an error."""
    X, y = generate_3d_test_data(random_state=0)
    with pytest.raises(ValueError, match=msg):
        RandomShapeletForestClassifier(**{"n_estimators": 2, **params}).fit(X, y)
