name: pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "tsml/**"
      - ".github/workflows/**"
      - "pyproject.toml"
  schedule:
    # every day at 1:30 AM UTC
    - cron: "30 1 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macOS-12, windows-2022 ]
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: python -m pip install .[dev,all_extras,unstable_extras]

      - name: Tests
        run: python -m pytest


  codecov:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Disable Numba JIT
        run: echo "NUMBA_DISABLE_JIT=1" >> $GITHUB_ENV

      - name: Install
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: python -m pip install .[dev,all_extras,unstable_extras]

      - name: Tests
        run: python -m pytest --cov=tsml_eval --cov-report=xml

      - uses: codecov/codecov-action@v3
